---
- name: Install Zabbix-agent
  apt:
    name: zabbix-agent
    state: present
  become: yes

- name: Copy Zabbix-agent configuration file
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Start and enable Zabbix-agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes
  become: yes
